'use client'

import { useState, useEffect, useRef } from 'react'
import Link from 'next/link'
import { Clock, Trophy, Brain, CheckCircle, XCircle, AlertTriangle, BookOpen } from 'lucide-react'

// ─── GATE Questions (30 questions mapped to 60 lessons) ───────────────────────

const GATE_QUESTIONS = [
  // Polymer Chemistry (6 questions)
  {
    id: 'gc1', subject: 'Polymer Chemistry', lessonSlug: 'polymerization-mechanisms-addition-vs-condensation',
    question: 'In free radical addition polymerization, the rate-determining step is:',
    options: ['Initiation', 'Propagation', 'Termination', 'Chain transfer'],
    correct: 0,
    explanation: 'Initiation is the slowest step in free radical polymerization — it involves homolytic dissociation of the initiator (e.g., BPO) and addition of the first radical to a monomer. Despite being rate-determining, propagation consumes most of the monomer because each initiation event adds thousands of monomer units.',
    marks: 1,
  },
  {
    id: 'gc2', subject: 'Polymer Chemistry', lessonSlug: 'glass-transition-temperature-tg-the-most-important-polymer-property',
    question: 'The glass transition temperature (Tg) of a polymer is best described as:',
    options: [
      'The temperature at which the polymer melts',
      'The temperature below which chain segment mobility ceases and the polymer becomes glassy',
      'The temperature at which crystallization begins',
      'The temperature at which polymer chains break',
    ],
    correct: 1,
    explanation: 'Tg marks the transition of amorphous polymer regions from a rubbery, mobile state to a rigid, glassy state upon cooling. Below Tg, backbone segment motion is frozen — the polymer is hard and brittle. Above Tg, segments can rotate freely — the material is soft and flexible. This governs nearly every end-use property.',
    marks: 1,
  },
  {
    id: 'gc3', subject: 'Polymer Chemistry', lessonSlug: 'molecular-weight-and-molecular-weight-distribution',
    question: 'The polydispersity index (PDI) of an ideal living anionic polymerization approaches:',
    options: ['0', '1.0', '2.0', '∞'],
    correct: 1,
    explanation: 'In living polymerization (e.g., anionic polymerization of styrene with n-BuLi), all chains initiate simultaneously and there is no termination. Every chain grows at the same rate and to the same length — giving a very narrow MWD with PDI (Mw/Mn) approaching 1.0. Commercial polymers typically have PDI 1.5–20 depending on the polymerization mechanism.',
    marks: 2,
  },
  {
    id: 'gc4', subject: 'Polymer Chemistry', lessonSlug: 'polymer-degradation-and-stabilization',
    question: 'Hindered amine light stabilizers (HALS) protect polyolefins from UV degradation by:',
    options: [
      'Absorbing UV radiation and converting it to heat',
      'Acting as chain scavengers — intercepting peroxy radicals to break the oxidative degradation cycle',
      'Increasing the crystallinity of the polymer',
      'Forming a UV-opaque surface film',
    ],
    correct: 1,
    explanation: 'HALS (e.g., Tinuvin 770) work by a radical scavenging mechanism — the hindered amine is oxidized to a nitroxyl radical that traps peroxy radicals (ROO•) generated by UV-induced oxidation. The nitroxyl radical is regenerated in a catalytic cycle, making HALS very efficient at low concentrations (0.1-0.5%). They do not absorb UV themselves — that is the role of UV absorbers like benzotriazoles.',
    marks: 2,
  },
  {
    id: 'gc5', subject: 'Polymer Chemistry', lessonSlug: 'copolymers-blends-and-alloys',
    question: 'ABS (Acrylonitrile-Butadiene-Styrene) is a terpolymer where the butadiene component primarily contributes:',
    options: ['Chemical resistance', 'Impact strength and toughness', 'Rigidity and modulus', 'Heat resistance'],
    correct: 1,
    explanation: 'In ABS, each monomer contributes distinct properties: Acrylonitrile → chemical resistance and heat resistance; Butadiene rubber phase → impact strength and toughness (the rubber particles cavitate and absorb energy during impact); Styrene → processability, rigidity, and surface finish. The dispersed rubber phase is the critical component that makes ABS the preferred material for high-impact applications like automotive dashboards.',
    marks: 1,
  },
  {
    id: 'gc6', subject: 'Polymer Chemistry', lessonSlug: 'crystallinity-and-morphology-in-polymers',
    question: 'Isotactic polypropylene has a higher melting point than atactic PP because:',
    options: [
      'It has higher molecular weight',
      'Regular spatial arrangement of methyl groups allows efficient chain packing into crystalline lamellae',
      'It contains more double bonds',
      'It has lower density',
    ],
    correct: 1,
    explanation: 'Isotactic PP has all methyl substituents on the same side of the backbone — this regular stereoregularity allows chains to pack into helical crystalline structures (3/1 helix, Tm ~165°C). Atactic PP has random methyl placement — cannot crystallize, remains amorphous with no distinct Tm, behaving as a sticky wax at room temperature. Ziegler-Natta catalysis produces isotactic PP; radical polymerization produces mostly atactic PP.',
    marks: 2,
  },

  // Polymer Processing (5 questions)
  {
    id: 'pp1', subject: 'Polymer Processing', lessonSlug: 'injection-moulding-process-parameters-and-defects',
    question: 'In injection moulding, the V-P (velocity-pressure) switchover is typically set at:',
    options: ['50% of cavity fill', '75% of cavity fill', '95-98% of cavity fill', '100% of cavity fill'],
    correct: 2,
    explanation: 'V-P switchover at 95-98% fill transitions from velocity-controlled filling to pressure-controlled packing. Switching too early (at 90%) leaves the cavity underfilled before pressure control begins. Switching too late (at 100%) causes flash as velocity drives melt past complete fill. The optimum leaves a small cushion for pressure to complete packing without overpacking.',
    marks: 1,
  },
  {
    id: 'pp2', subject: 'Polymer Processing', lessonSlug: 'extrusion-fundamentals-the-backbone-of-plastic-processing',
    question: 'The output rate of a single-screw extruder is primarily controlled by:',
    options: ['Barrel temperature only', 'Screw speed (RPM) — the primary variable for output control', 'Die pressure only', 'Feed hopper level'],
    correct: 1,
    explanation: 'In single-screw extrusion, screw speed is the primary output control variable — doubling RPM approximately doubles output (within the stable operating range). Barrel temperature primarily controls melt quality and viscosity. Die pressure is a consequence of output rate and die resistance. Feed hopper level affects output only if the extruder becomes starve-fed, which is abnormal operation.',
    marks: 1,
  },
  {
    id: 'pp3', subject: 'Polymer Processing', lessonSlug: 'melt-flow-index-mfi-measurement-significance-and-indian-standards',
    question: 'MFI is measured at 230°C/2.16kg for PP. A PP grade with MFI = 30 g/10min is most suitable for:',
    options: [
      'HDPE pressure pipe (requires high MW for strength)',
      'Thin-wall injection moulded parts and fibres (requires easy flow)',
      'Blow moulded containers (requires high melt strength)',
      'Rotational moulding (requires powder form)',
    ],
    correct: 1,
    explanation: 'High MFI = low molecular weight = low viscosity = easy flow. MFI 30 PP flows easily, filling thin-wall moulds and drawing into fine fibres without excessive pressure. Pipe grades need MFI 0.3-0.8 (high MW for pressure resistance). Blow moulding needs MFI 0.5-3 (high melt strength to support the parison). The MFI selection is the first material selection decision in any PP processing application.',
    marks: 2,
  },
  {
    id: 'pp4', subject: 'Polymer Processing', lessonSlug: 'rheological-testing-understanding-melt-flow-behavior',
    question: 'Most polymer melts exhibit pseudoplastic (shear-thinning) behavior. This means:',
    options: [
      'Viscosity increases with increasing shear rate',
      'Viscosity is independent of shear rate (Newtonian)',
      'Viscosity decreases with increasing shear rate — favorable for processing',
      'Viscosity is time-dependent',
    ],
    correct: 2,
    explanation: 'Pseudoplastic (shear-thinning) behavior — viscosity decreases as shear rate increases — is beneficial for polymer processing. At the high shear rates in injection moulding gates and extruder screws, viscosity drops dramatically, allowing the polymer to flow with much less pressure than its low-shear viscosity would predict. This is why high-MW polymers (which have very high zero-shear viscosity) can still be processed on standard equipment at practical pressures.',
    marks: 2,
  },
  {
    id: 'pp5', subject: 'Polymer Processing', lessonSlug: 'thermoforming-rotational-moulding-and-compression-moulding',
    question: 'In thermoforming, the minimum achievable wall thickness occurs at:',
    options: [
      'The top of the formed part (nearest the mould)',
      'The corners and deep draw areas — where the sheet is stretched most',
      'The centre of the part',
      'The flange area',
    ],
    correct: 1,
    explanation: 'During thermoforming, the sheet stretches biaxially as it conforms to the mould. The highest stretch ratio — and therefore the thinnest wall — occurs at corners, radii, and areas of deep draw where the sheet has traveled the greatest distance from its original plane. Parison programming in blow moulding and plug-assist in thermoforming both address this non-uniform wall thickness distribution.',
    marks: 1,
  },

  // Polymer Testing (4 questions)
  {
    id: 'pt1', subject: 'Polymer Testing', lessonSlug: 'tensile-and-flexural-testing-measuring-mechanical-strength',
    question: 'Young\'s modulus (elastic modulus) of a polymer is determined from the tensile stress-strain curve as:',
    options: [
      'Stress at break divided by strain at break',
      'Slope of the linear (elastic) region of the stress-strain curve',
      'Area under the entire stress-strain curve',
      'Maximum stress divided by gauge length',
    ],
    correct: 1,
    explanation: "Young's modulus = stress/strain in the initial linear (elastic) region where Hooke's law applies. It represents the material's stiffness — resistance to elastic deformation. The area under the entire curve = toughness (energy absorbed to fracture). Stress at break = ultimate tensile strength. These are three distinct and independently important material properties measured from a single tensile test.",
    marks: 1,
  },
  {
    id: 'pt2', subject: 'Polymer Testing', lessonSlug: 'thermal-analysis-dsc-tga-and-hdt-testing',
    question: 'In TGA (Thermogravimetric Analysis) of a carbon black-filled EPDM rubber, the weight loss at ~500°C in nitrogen atmosphere represents:',
    options: [
      'Carbon black decomposition',
      'Polymer (rubber) decomposition — the organic phase pyrolyzes',
      'Water evaporation',
      'Plasticizer volatilization',
    ],
    correct: 1,
    explanation: 'TGA in nitrogen (inert atmosphere) decomposes organic materials but not carbon black. Weight loss sequence for carbon black-filled rubber: <150°C (moisture/volatiles), 300-550°C (polymer/rubber decomposition), residue = carbon black + inorganic fillers + ash. Switching to air after the polymer stage burns the carbon black, giving its weight fraction. This quantitative compositional analysis is the primary industrial use of TGA for rubber compounds.',
    marks: 2,
  },
  {
    id: 'pt3', subject: 'Polymer Testing', lessonSlug: 'impact-testing-izod-charpy-and-drop-weight',
    question: 'Notching a specimen before Izod/Charpy impact testing is done to:',
    options: [
      'Reduce the specimen size',
      'Introduce a stress concentrator that ensures fracture initiates at a defined point — testing worst-case impact resistance',
      'Increase the impact energy measurement accuracy',
      'Prevent the specimen from slipping in the fixture',
    ],
    correct: 1,
    explanation: 'The notch creates a controlled stress concentration that guarantees fracture initiates at the notch root rather than elsewhere. This gives reproducible results and represents the worst-case scenario (a pre-existing defect or sharp corner in a real part). Notch sensitivity is a critical material property — some materials (e.g., nylon, PC) have dramatically different notched vs unnotched impact values, which directly affects design decisions about sharp corners in moulded parts.',
    marks: 1,
  },
  {
    id: 'pt4', subject: 'Polymer Testing', lessonSlug: 'quality-control-bis-and-astm-standards-for-polymer-testing',
    question: 'The IS 13360 series of standards specifies test methods for plastics in India. IS 13360 is technically equivalent to:',
    options: ['ASTM D series', 'ISO 10350 series', 'ISO 527 / ISO 178 / ISO 179 (specific test standards)', 'DIN standards'],
    correct: 2,
    explanation: 'IS 13360 is BIS\'s adoption of specific ISO test standards for plastics. For example: IS 13360 Part 5 Sec 4 = ISO 179 (Charpy impact); IS 13360 Part 4 Sec 1 = ISO 527 (tensile); IS 13360 Part 4 Sec 5 = ISO 178 (flexural). Understanding this equivalence is essential for QC engineers who must cite the correct standard in test reports for domestic (BIS) and export (ISO) markets.',
    marks: 2,
  },

  // Rubber Technology (3 questions)
  {
    id: 'rt1', subject: 'Rubber Technology', lessonSlug: 'vulcanization-the-chemistry-that-made-rubber-useful',
    question: 'The optimum cure time (t90) in a vulcanization rheometer (MDR) represents:',
    options: [
      'Time to reach maximum torque',
      'Time to reach 90% of the maximum torque development — the standard cure specification point',
      'Time for complete marching cure',
      'Time for scorch (premature vulcanization)',
    ],
    correct: 1,
    explanation: 'In a Moving Die Rheometer (MDR), torque increases as crosslinks form during cure. t90 = time to reach 90% of (maximum torque - minimum torque) + minimum torque. This is the standard industry specification for press cure time because it represents near-complete crosslink development while avoiding overcure (reversion in NR, marching cure in EPDM). ts2 (scorch time = 2 unit torque rise above minimum) specifies processing safety.',
    marks: 2,
  },
  {
    id: 'rt2', subject: 'Rubber Technology', lessonSlug: 'rubber-compounding-fillers-carbon-black-and-additives',
    question: 'The primary reinforcing mechanism of carbon black in rubber is:',
    options: [
      'Increasing the density of the compound',
      'Physical and chemical bonding between carbon black surface and rubber chains — restricting chain mobility and transferring stress to the rigid filler network',
      'Reducing the crosslink density',
      'Improving electrical insulation',
    ],
    correct: 1,
    explanation: 'Carbon black reinforcement involves: (1) Physical adsorption of rubber chains onto the high-surface-area carbon black particle surface (bound rubber); (2) Filler-filler network formation above the percolation threshold; (3) Hydrodynamic effect (rigid particles increase effective viscosity). Together these give a 10-100× improvement in tensile strength and abrasion resistance over unfilled rubber. The aggregate structure (secondary particle shape) and surface area are the two most important carbon black parameters for reinforcement.',
    marks: 2,
  },
  {
    id: 'rt3', subject: 'Rubber Technology', lessonSlug: 'natural-rubber-vs-synthetic-rubbers-selection-guide',
    question: 'NBR (Nitrile Butadiene Rubber) is preferred over NR for oil seals because:',
    options: [
      'NBR has higher tensile strength than NR',
      'The polar acrylonitrile units in NBR resist swelling in non-polar oils — NR swells extensively in hydrocarbon oils',
      'NBR has better low temperature flexibility',
      'NBR is cheaper than NR',
    ],
    correct: 1,
    explanation: '"Like dissolves like" — non-polar NR swells in non-polar hydrocarbon oils (fuel, lubricants), causing seal failure. NBR contains polar acrylonitrile groups (18-50% ACN content) in the backbone — the polarity difference between NBR and non-polar oil prevents swelling. Higher ACN content = better oil resistance but poorer low-temperature flexibility. This structure-property relationship directly determines material selection for automotive oil seals, fuel hoses, and hydraulic system seals.',
    marks: 1,
  },

  // Recycling Technology (3 questions)
  {
    id: 'rcy1', subject: 'Recycling Technology', lessonSlug: 'mechanical-recycling-processes-sorting-washing-and-reprocessing',
    question: 'The float-sink separation tank in PET bottle recycling separates PET from PE/PP caps because:',
    options: [
      'PET is magnetic, PE/PP are not',
      'PET density (1.38 g/cm³) causes it to sink in water while PE (0.95) and PP (0.91) float',
      'PET is soluble in water',
      'PE/PP are colored while PET is clear',
    ],
    correct: 1,
    explanation: 'Float-sink separation exploits density differences: PET (1.33-1.40 g/cm³) sinks in water (1.0 g/cm³); HDPE/LDPE/PP (0.91-0.97 g/cm³) float. This single-step physical separation removes all polyolefin contamination from PET flake after granulation — critical because even 50 ppm PE contamination causes crystallization defects in recycled PET melt. NIR sorting identifies and separates different polymer types in the whole-bottle form before granulation.',
    marks: 1,
  },
  {
    id: 'rcy2', subject: 'Recycling Technology', lessonSlug: 'chemical-recycling-pyrolysis-depolymerization-and-feedstock-recovery',
    question: 'Depolymerization of PET by glycolysis produces:',
    options: [
      'Terephthalic acid (TPA) and ethylene glycol (EG)',
      'Bis(2-hydroxyethyl) terephthalate (BHET) — a monomer/oligomer that can be repolymerized',
      'Pyrolysis oil and syngas',
      'Carbon black and methane',
    ],
    correct: 1,
    explanation: 'Glycolysis reacts PET with excess ethylene glycol at 180-240°C with catalyst — the ester bonds are transesterified, not hydrolyzed, producing BHET (Bis-2-HydroxyEthyl Terephthalate). BHET is then repolymerized to virgin-quality PET. This is distinct from hydrolysis (which produces TPA + EG) and methanolysis (which produces DMT + EG). Glycolysis is the most commercially established chemical recycling route for PET — used by Loop Industries and others.',
    marks: 2,
  },
  {
    id: 'rcy3', subject: 'Recycling Technology', lessonSlug: 'extended-producer-responsibility-epr-and-regulatory-frameworks',
    question: 'Under India\'s PWM Rules 2022 (EPR framework), EPR certificates are:',
    options: [
      'Issued by BIS to certify recycled content',
      'Tradeable credits generated by registered recyclers and purchased by brand owners (PIBOs) to offset their plastic footprint obligations',
      'Import permits for recycled plastic',
      'Quality certificates for recycled material',
    ],
    correct: 1,
    explanation: 'India\'s EPR framework creates a market mechanism: registered recyclers process plastic waste and generate EPR certificates on the CPCB portal (one certificate per tonne recycled). PIBOs who cannot meet their own recycling targets purchase these certificates to fulfill their regulatory obligations. This creates a financial incentive for recycling investment and a direct payment stream from brand owners to recyclers — the mechanism that makes plastic recycling economics viable at scale in India.',
    marks: 2,
  },

  // Sustainable Plastics (2 questions)
  {
    id: 'sp1', subject: 'Sustainable Plastics', lessonSlug: 'polylactic-acid-pla-synthesis-properties-and-commercial-reality',
    question: 'PLA (Polylactic Acid) is produced from lactic acid by:',
    options: [
      'Direct condensation polymerization only',
      'Ring-opening polymerization (ROP) of lactide — the cyclic dimer of lactic acid — giving controlled MW and narrow PDI',
      'Free radical polymerization',
      'Ionic polymerization in water',
    ],
    correct: 1,
    explanation: 'Direct condensation of lactic acid gives low MW PLA due to water removal limitations. Commercial high-MW PLA (NatureWorks Ingeo) uses a two-step process: (1) condensation of lactic acid to low-MW prepolymer + lactide (cyclic dimer) formation by depolymerization; (2) ring-opening polymerization of purified lactide with Sn(Oct)2 catalyst, giving high-MW PLA with controlled stereoregularity (L/D ratio determines Tm). This route enables the Mw >100,000 g/mol needed for commercial fiber and packaging applications.',
    marks: 2,
  },
  {
    id: 'sp2', subject: 'Sustainable Plastics', lessonSlug: 'microplastics-sources-impacts-and-the-remediation-frontier',
    question: 'Primary microplastics differ from secondary microplastics in that:',
    options: [
      'Primary microplastics are larger than 5mm',
      'Primary microplastics are manufactured at micro-scale (nurdles, microbeads, fibres) while secondary microplastics form by fragmentation of larger plastic items',
      'Primary microplastics are biodegradable',
      'Primary microplastics only come from packaging',
    ],
    correct: 1,
    explanation: 'Primary microplastics are intentionally manufactured <5mm: resin pellets (nurdles) lost during transport, microbeads in personal care products (now banned in many countries), and synthetic textile fibres shed during washing. Secondary microplastics form when UV radiation, mechanical abrasion, and weathering fragment larger plastic items — this is the dominant source by mass in the environment. Tyre wear particles (secondary) are estimated to be the largest single source of microplastic pollution globally.',
    marks: 1,
  },

  // Polymer Composites (3 questions)
  {
    id: 'pc1', subject: 'Polymer Composites', lessonSlug: 'introduction-to-polymer-composites-matrix-reinforcement-and-interface',
    question: 'The critical fibre length (lc) in short fibre reinforced composites is the minimum length at which:',
    options: [
      'The fibre can be processed by injection moulding',
      'Sufficient shear stress transfer from matrix to fibre occurs to load the fibre to its tensile strength — fibres shorter than lc are pulled out rather than fracturing',
      'The fibre starts to break during compounding',
      'The composite reaches maximum density',
    ],
    correct: 1,
    explanation: 'Critical fibre length lc = (σf × d) / (2 × τi), where σf = fibre tensile strength, d = fibre diameter, τi = interfacial shear strength. Below lc, the matrix-fibre interface fails (pull-out) before the fibre fractures — the fibre is underutilized. Above lc, the fibre can be loaded to its full strength — maximum reinforcement efficiency. This is why aspect ratio (length/diameter) is the key parameter for short fibre reinforcement: glass fibre (10μm diameter) needs lc ~ 0.5-1mm in nylon.',
    marks: 2,
  },
  {
    id: 'pc2', subject: 'Polymer Composites', lessonSlug: 'glass-fibre-reinforced-plastics-gfrp-processing-and-applications',
    question: 'E-glass fibre is coated with a silane coupling agent primarily to:',
    options: [
      'Improve the colour of the glass fibre',
      'Create chemical bonds between the glass surface (Si-OH groups) and the polymer matrix — dramatically improving interfacial adhesion and wet strength retention',
      'Reduce the density of the glass fibre',
      'Increase the electrical conductivity',
    ],
    correct: 1,
    explanation: 'Silane coupling agents (e.g., aminosilane for epoxy, vinylsilane for polyester) have dual functionality: the silane end (Si-OCH3 groups) reacts with Si-OH groups on the glass surface; the organic end is compatible with or reactive toward the polymer matrix. This creates a covalent bridge across the hydrophilic glass/hydrophobic polymer interface — improving dry strength by 20-40% and retaining strength in wet conditions where untreated glass fibre composites lose 50-60% strength due to moisture debonding.',
    marks: 2,
  },
  {
    id: 'pc3', subject: 'Polymer Composites', lessonSlug: 'composite-design-failure-modes-and-testing',
    question: 'Delamination in carbon fibre reinforced polymer (CFRP) laminates is a failure mode that occurs:',
    options: [
      'When carbon fibres break in tension',
      'When the resin matrix cracks between plies due to interlaminar shear or tensile stress — separating layers without fibre fracture',
      'When the composite melts at high temperature',
      'When carbon fibres debond from the matrix within a single ply',
    ],
    correct: 1,
    explanation: 'Delamination (interlaminar separation) is the dominant failure mode in CFRP laminates under out-of-plane loading, impact, or fatigue. The interlaminar fracture toughness (GIc, GIIc) is very low in standard CFRP because the only material between plies is brittle epoxy resin — no fibre bridging. Solutions: toughened resin systems, interleaving, z-pinning, 3D woven architectures. This is why CFRP aircraft panels require regular NDT (non-destructive testing) inspection for impact-induced delamination.',
    marks: 2,
  },

  // Medical Plastics (2 questions)
  {
    id: 'mp1', subject: 'Medical Plastics', lessonSlug: 'biocompatibility-iso-10993-and-the-science-of-safe-polymer-body-contact',
    question: 'The Sterility Assurance Level (SAL) required for terminally sterilized medical devices is:',
    options: ['10⁻³ (1 in 1,000 devices non-sterile)', '10⁻⁶ (1 in 1,000,000 devices non-sterile)', '10⁻⁹', '10⁰ (100% sterile)'],
    correct: 1,
    explanation: 'SAL 10⁻⁶ means the probability that any single device remains non-sterile after the validated sterilization process is ≤1 in 1,000,000. This is the internationally accepted standard for terminal sterilization of medical devices (ISO 11135 for EtO, ISO 11137 for radiation). It is validated by bioburden testing (pre-sterilization microbial load) and overkill or bioburden-based approaches to determine minimum dose. SAL 10⁻⁶ is a regulatory requirement in all major markets.',
    marks: 1,
  },
  {
    id: 'mp2', subject: 'Medical Plastics', lessonSlug: 'sterilization-methods-and-polymer-compatibility',
    question: 'PEEK is stable under gamma radiation sterilization while standard PP becomes brittle. The fundamental reason is:',
    options: [
      'PEEK has higher molecular weight than PP',
      'PEEK\'s aromatic backbone is radiation-stable — aromatic rings dissipate radical energy by resonance, while PP\'s aliphatic tertiary carbons are highly susceptible to chain scission',
      'PEEK is crystalline while PP is amorphous',
      'PEEK contains fluorine atoms that protect against radiation',
    ],
    correct: 1,
    explanation: 'Aromatic rings in PEEK\'s backbone act as radical sinks — they can absorb and dissipate the energy of gamma-induced radicals without undergoing chain scission or crosslinking. In contrast, PP\'s tertiary C-H bonds (at every third carbon) are the weakest points in the chain — gamma radiation preferentially generates radicals here, leading to beta-scission (chain breaking) and MW reduction. This fundamental difference in backbone chemistry explains why aromatic engineering polymers (PEEK, PSU, PEI) are inherently radiation-stable while aliphatic polyolefins are not.',
    marks: 2,
  },

  // Entrepreneurship (2 questions)
  {
    id: 'ep1', subject: 'Entrepreneurship', lessonSlug: 'funding-government-schemes-and-project-report-basics',
    question: 'Under the PMEGP scheme, what is the maximum project cost eligible for subsidy for a manufacturing unit?',
    options: ['₹10 lakh', '₹25 lakh', '₹50 lakh', '₹1 crore'],
    correct: 2,
    explanation: 'PMEGP (Prime Minister\'s Employment Generation Programme) covers manufacturing projects up to ₹50 lakh with a government subsidy of 15-35% of project cost (category and location dependent). The bank finances 55-75% as term loan and the promoter contributes 5-10% equity. For service sector, the maximum is ₹20 lakh. This makes PMEGP the most accessible startup financing scheme for polymer engineering graduates starting small-scale processing units.',
    marks: 1,
  },
  {
    id: 'ep2', subject: 'Entrepreneurship', lessonSlug: 'running-a-plastics-business-quality-compliance-bis-certification-and-export',
    question: 'To export plastic products from India, the minimum mandatory registration required is:',
    options: [
      'ISO 9001 certification',
      'IEC (Import Export Code) from DGFT — a 10-digit code issued online, mandatory for any import or export transaction',
      'BIS certification',
      'PLEXCONCIL membership',
    ],
    correct: 1,
    explanation: 'IEC (Importer Exporter Code) from DGFT (Directorate General of Foreign Trade) is the only mandatory requirement for any import or export from India — issued online at dgft.gov.in within 1-2 working days, currently free of cost. RCMC (from export promotion council like PLEXCONCIL for plastics) is needed to claim export incentives but not for the transaction itself. ISO 9001 and BIS are quality certifications, not export authorizations.',
    marks: 1,
  },
]

// ─── Types ────────────────────────────────────────────────────────────────────

type QuizState = 'setup' | 'active' | 'submitted'
type AnswerMap = Record<string, number>

const SUBJECT_COLORS: Record<string, string> = {
  'Polymer Chemistry': '#1D4ED8',
  'Polymer Processing': '#EA580C',
  'Polymer Testing': '#7C3AED',
  'Rubber Technology': '#EA580C',
  'Recycling Technology': '#15803D',
  'Sustainable Plastics': '#15803D',
  'Polymer Composites': '#1D4ED8',
  'Medical Plastics': '#7C3AED',
  'Entrepreneurship': '#CA8A04',
}

// ─── Timer Component ──────────────────────────────────────────────────────────

function Timer({ seconds, onTimeout }: { seconds: number; onTimeout: () => void }) {
  const [remaining, setRemaining] = useState(seconds)
  const intervalRef = useRef<NodeJS.Timeout | null>(null)

  useEffect(() => {
    intervalRef.current = setInterval(() => {
      setRemaining(prev => {
        if (prev <= 1) {
          clearInterval(intervalRef.current!)
          onTimeout()
          return 0
        }
        return prev - 1
      })
    }, 1000)
    return () => clearInterval(intervalRef.current!)
  }, [onTimeout])

  const mins = Math.floor(remaining / 60)
  const secs = remaining % 60
  const isUrgent = remaining < 300 // last 5 minutes

  return (
    <div
      className="flex items-center gap-2 border-4 border-ink px-4 py-2 font-mono font-black text-lg"
      style={{ backgroundColor: isUrgent ? '#EA580C' : '#0A0A0A', color: isUrgent ? 'white' : '#FACC15' }}
    >
      <Clock className="w-5 h-5" />
      {String(mins).padStart(2, '0')}:{String(secs).padStart(2, '0')}
    </div>
  )
}

// ─── Score Report ─────────────────────────────────────────────────────────────

function ScoreReport({ answers, timeTaken }: { answers: AnswerMap; timeTaken: number }) {
  const totalMarks = GATE_QUESTIONS.reduce((a, q) => a + q.marks, 0)
  let scored = 0
  let correct = 0
  let wrong = 0
  let unattempted = 0

  GATE_QUESTIONS.forEach(q => {
    if (answers[q.id] === undefined) {
      unattempted++
    } else if (answers[q.id] === q.correct) {
      scored += q.marks
      correct++
    } else {
      // GATE has negative marking: -1/3 for 1-mark, -2/3 for 2-mark
      scored -= q.marks / 3
      wrong++
    }
  })

  const pct = Math.round((scored / totalMarks) * 100)
  const color = pct >= 70 ? '#15803D' : pct >= 50 ? '#CA8A04' : '#EA580C'
  const mins = Math.floor(timeTaken / 60)
  const secs = timeTaken % 60

  // Subject-wise breakdown
  const subjects = GATE_QUESTIONS.map(q => q.subject).filter((value, index, self) => self.indexOf(value) === index)
  const subjectBreakdown = subjects.map(sub => {
    const subQs = GATE_QUESTIONS.filter(q => q.subject === sub)
    const subMarks = subQs.reduce((a, q) => a + q.marks, 0)
    let subScored = 0
    subQs.forEach(q => {
      if (answers[q.id] === q.correct) subScored += q.marks
      else if (answers[q.id] !== undefined) subScored -= q.marks / 3
    })
    return { subject: sub, scored: Math.max(0, subScored), total: subMarks, pct: Math.round((Math.max(0, subScored) / subMarks) * 100) }
  })

  return (
    <div className="space-y-5 animate-fade-up">

      {/* Main score */}
      <div className="border-4 border-ink overflow-hidden" style={{ boxShadow: `6px 6px 0px 0px ${color}` }}>
        <div className="border-b-4 border-ink px-6 py-5 text-center" style={{ backgroundColor: color }}>
          <div className="font-display text-6xl font-black text-white mb-1">
            {Math.max(0, scored).toFixed(2)}
            <span className="text-2xl text-white/50">/{totalMarks}</span>
          </div>
          <div className="font-mono text-[10px] text-white/70 uppercase tracking-widest">GATE Score Estimate</div>
        </div>
        <div className="p-5 bg-canvas">
          <div className="grid grid-cols-4 gap-3 mb-5">
            {[
              { val: correct, label: 'Correct', color: '#15803D', bg: '#F0FDF4' },
              { val: wrong, label: 'Wrong', color: '#EA580C', bg: '#FFF7ED' },
              { val: unattempted, label: 'Unattempted', color: '#6B7280', bg: '#F9FAFB' },
              { val: `${mins}m ${secs}s`, label: 'Time taken', color: '#1D4ED8', bg: '#EFF6FF' },
            ].map(s => (
              <div key={s.label} className="border-4 border-ink p-3 text-center shadow-hard-sm" style={{ backgroundColor: s.bg }}>
                <div className="font-display text-2xl font-black" style={{ color: s.color }}>{s.val}</div>
                <div className="font-mono text-[8px] text-ink/50 uppercase tracking-wider mt-0.5">{s.label}</div>
              </div>
            ))}
          </div>

          <div className="border-4 border-ink p-4 mb-4" style={{ backgroundColor: '#FEFCE8' }}>
            <p className="font-mono text-[10px] text-ink/60 uppercase tracking-wider">
              GATE uses negative marking: −1/3 mark for wrong 1-mark questions, −2/3 for wrong 2-mark questions. Unattempted questions carry zero penalty.
            </p>
          </div>

          <div className="flex gap-3 flex-wrap">
            <Link href="/practice" className="cn-btn-yellow text-sm flex-1 justify-center">
              <Zap className="w-4 h-4" /> Practice More
            </Link>
            <Link href="/ai-tutor" className="cn-btn-black text-sm flex-1 justify-center">
              <Brain className="w-4 h-4" /> Ask AI Tutor
            </Link>
          </div>
        </div>
      </div>

      {/* Subject breakdown */}
      <div className="border-4 border-ink overflow-hidden shadow-hard">
        <div className="border-b-4 border-ink px-5 py-3 bg-ink">
          <span className="font-mono text-[10px] font-black text-yellow-bright uppercase tracking-widest">Subject-wise Performance</span>
        </div>
        <div className="divide-y-2 divide-ink/10">
          {subjectBreakdown.map(s => {
            const color = SUBJECT_COLORS[s.subject] ?? '#1D4ED8'
            return (
              <div key={s.subject} className="px-5 py-4">
                <div className="flex items-center justify-between mb-2">
                  <span className="font-mono text-[10px] font-bold text-ink uppercase tracking-wide">{s.subject}</span>
                  <span className="font-mono text-[10px] font-black" style={{ color }}>{s.scored}/{s.total} marks · {s.pct}%</span>
                </div>
                <div className="border-2 border-ink h-3 overflow-hidden">
                  <div className="h-full" style={{ width: `${s.pct}%`, backgroundColor: color }} />
                </div>
              </div>
            )
          })}
        </div>
      </div>

      {/* Answer review */}
      <div className="space-y-3">
        <div className="font-mono text-[10px] font-bold text-ink/50 uppercase tracking-widest border-b-4 border-ink pb-3">
          Full Answer Review ({GATE_QUESTIONS.length} questions)
        </div>
        {GATE_QUESTIONS.map((q, idx) => {
          const userAnswer = answers[q.id]
          const isCorrect = userAnswer === q.correct
          const isUnattempted = userAnswer === undefined
          const borderColor = isUnattempted ? '#D1D5DB' : isCorrect ? '#15803D' : '#EA580C'


          return (
            <div key={q.id} className="border-4 border-ink overflow-hidden" style={{ boxShadow: `2px 2px 0px 0px ${borderColor}` }}>
              <div className="border-b-4 border-ink px-4 py-2 flex items-center gap-3" style={{ backgroundColor: borderColor }}>
                {isUnattempted
                  ? <AlertTriangle className="w-4 h-4 text-white" />
                  : isCorrect
                  ? <CheckCircle className="w-4 h-4 text-white" />
                  : <XCircle className="w-4 h-4 text-white" />}
                <span className="font-mono text-[9px] font-black text-white uppercase">
                  Q{idx + 1} · {q.marks} mark{q.marks > 1 ? 's' : ''} · {isUnattempted ? 'Not attempted' : isCorrect ? 'Correct' : `Wrong — Answer: ${q.options[q.correct].slice(0, 30)}`}
                </span>
                <span className="font-mono text-[8px] border border-white/40 text-white px-1.5 ml-auto uppercase">{q.subject}</span>
              </div>
              <div className="p-4 bg-canvas">
                <p className="font-bold text-sm text-ink mb-3">{q.question}</p>
                <div className="space-y-1.5 mb-3">
                  {q.options.map((opt, optIdx) => {
                    const isCorrectOpt = optIdx === q.correct
                    const isUserChoice = optIdx === userAnswer
                    return (
                      <div key={optIdx} className="flex items-center gap-2 px-3 py-2 border-2 text-sm"
                        style={{
                          borderColor: isCorrectOpt ? '#15803D' : isUserChoice ? '#EA580C' : '#E5E7EB',
                          backgroundColor: isCorrectOpt ? '#F0FDF4' : isUserChoice ? '#FFF7ED' : 'white',
                        }}
                      >
                        <span className="font-mono text-[9px] font-black w-4 flex-shrink-0" style={{ color: isCorrectOpt ? '#15803D' : isUserChoice ? '#EA580C' : '#9CA3AF' }}>
                          {['A', 'B', 'C', 'D'][optIdx]}
                        </span>
                        <span className="flex-1 text-ink">{opt}</span>
                        {isCorrectOpt && <CheckCircle className="w-3.5 h-3.5 text-green flex-shrink-0" />}
                        {isUserChoice && !isCorrectOpt && <XCircle className="w-3.5 h-3.5 text-orange flex-shrink-0" />}
                      </div>
                    )
                  })}
                </div>
                <div className="border-l-4 pl-3 py-1" style={{ borderColor, backgroundColor: isCorrect ? '#F0FDF4' : isUnattempted ? '#F9FAFB' : '#FFF7ED' }}>
                  <p className="font-mono text-[9px] font-bold uppercase tracking-wider mb-1" style={{ color: borderColor }}>Explanation</p>
                  <p className="text-sm text-ink leading-relaxed">{q.explanation}</p>
                </div>
                <Link href={`/lessons/${q.lessonSlug}`} className="font-mono text-[9px] text-ink/40 hover:text-ink mt-2 flex items-center gap-1 uppercase tracking-wider transition-colors">
                  <BookOpen className="w-3 h-3" /> Related Lesson →
                </Link>
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}

// Add missing Zap import
const Zap = ({ className }: { className?: string }) => (
  <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
  </svg>
)

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function GATEMockPage() {
  const [state, setState] = useState<QuizState>('setup')
  const [answers, setAnswers] = useState<AnswerMap>({})
  const [currentQ, setCurrentQ] = useState(0)
  const [startTime, setStartTime] = useState<number>(0)
  const [timeTaken, setTimeTaken] = useState(0)
  const [flagged, setFlagged] = useState<Set<string>>(new Set())

  const TOTAL_TIME = 60 * 60 // 60 minutes

  const handleStart = () => {
    setStartTime(Date.now())
    setAnswers({})
    setCurrentQ(0)
    setFlagged(new Set())
    setState('active')
  }

  const handleSubmit = () => {
    setTimeTaken(Math.round((Date.now() - startTime) / 1000))
    setState('submitted')
  }

  const handleSelect = (optIdx: number) => {
    setAnswers(prev => ({ ...prev, [GATE_QUESTIONS[currentQ].id]: optIdx }))
  }

  const toggleFlag = () => {
    const id = GATE_QUESTIONS[currentQ].id
    setFlagged(prev => {
      const next = new Set(prev)
      if (next.has(id)) {
        next.delete(id)
      } else {
        next.add(id)
      }
      return next
    })
  }

  const answered = Object.keys(answers).length
  const currentQuestion = GATE_QUESTIONS[currentQ]
  const currentAnswer = answers[currentQuestion?.id]
  const isFlagged = flagged.has(currentQuestion?.id)

  return (
    <div className="min-h-screen bg-canvas">
      <div className="h-2 bg-violet" />

      {/* Header */}
      <div className="border-b-4 border-ink bg-ink px-6 py-4 flex items-center justify-between flex-wrap gap-3">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 bg-violet border-4 border-violet flex items-center justify-center">
            <Trophy className="w-4 h-4 text-white" />
          </div>
          <div>
            <div className="font-display text-lg font-black text-white">GATE Mock Test</div>
            <div className="font-mono text-[9px] text-white/40 uppercase tracking-wider">
              Polymer Science · 30 Questions · 60 Minutes · Negative Marking
            </div>
          </div>
        </div>
        {state === 'active' && (
          <Timer seconds={TOTAL_TIME} onTimeout={handleSubmit} />
        )}
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8">

        {/* Setup screen */}
        {state === 'setup' && (
          <div className="space-y-5">
            <div className="border-4 border-ink overflow-hidden" style={{ boxShadow: '6px 6px 0px 0px #7C3AED' }}>
              <div className="border-b-4 border-ink px-6 py-5 bg-violet">
                <h1 className="font-display text-3xl font-black text-white mb-1">GATE Polymer Science Mock Test</h1>
                <p className="font-mono text-[10px] text-white/60 uppercase tracking-wider">Simulated exam · Based on actual GATE syllabus</p>
              </div>
              <div className="p-6 bg-canvas">
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
                  {[
                    { val: '30', label: 'Questions', color: '#7C3AED' },
                    { val: '35', label: 'Total Marks', color: '#1D4ED8' },
                    { val: '60', label: 'Minutes', color: '#EA580C' },
                    { val: '−1/3', label: 'Negative Marking', color: '#CA8A04' },
                  ].map(s => (
                    <div key={s.label} className="border-4 border-ink p-4 text-center shadow-hard-sm" style={{ backgroundColor: s.color + '12' }}>
                      <div className="font-display text-3xl font-black" style={{ color: s.color }}>{s.val}</div>
                      <div className="font-mono text-[9px] text-ink/50 uppercase tracking-wider mt-1">{s.label}</div>
                    </div>
                  ))}
                </div>

                <div className="border-4 border-ink p-4 mb-6" style={{ backgroundColor: '#FFF7ED' }}>
                  <p className="font-mono text-[9px] font-bold text-orange uppercase tracking-wider mb-2">Exam Rules</p>
                  <ul className="space-y-1">
                    {[
                      'Each 1-mark wrong answer deducts 1/3 mark',
                      'Each 2-mark wrong answer deducts 2/3 mark',
                      'Unattempted questions carry zero penalty',
                      'You can navigate between questions freely',
                      'Flag questions to review before submitting',
                      'Timer runs continuously — submit before 60 minutes',
                    ].map(rule => (
                      <li key={rule} className="text-sm text-ink flex items-center gap-2">
                        <div className="w-1.5 h-1.5 bg-orange rounded-full flex-shrink-0" />
                        {rule}
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="mb-6">
                  <p className="font-mono text-[9px] font-bold text-ink/50 uppercase tracking-wider mb-2">Subjects Covered</p>
                  <div className="flex flex-wrap gap-2">
                    {Object.entries(SUBJECT_COLORS).map(([sub, color]) => (
                      <span key={sub} className="font-mono text-[9px] border-2 px-2 py-0.5 uppercase tracking-wider" style={{ borderColor: color, color }}>
                        {sub.replace('Polymer ', '')}
                      </span>
                    ))}
                  </div>
                </div>

                <button onClick={handleStart} className="cn-btn-black w-full justify-center text-sm">
                  <Trophy className="w-4 h-4" /> Start Mock Test — 60 Minutes
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Active exam */}
        {state === 'active' && currentQuestion && (
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">

            {/* Question column */}
            <div className="lg:col-span-3 space-y-6">
              {/* Progress and indicators */}
              <div className="flex items-center justify-between flex-wrap gap-2">
                <span className="font-mono text-xs font-bold text-ink/50 uppercase tracking-wider">
                  Question {currentQ + 1} of {GATE_QUESTIONS.length}
                </span>
                <span className="font-mono text-xs font-bold text-ink/50 uppercase tracking-wider">
                  {answered}/{GATE_QUESTIONS.length} Answered
                </span>
              </div>

              {/* Question card */}
              <div className="border-4 border-ink bg-canvas shadow-hard overflow-hidden" style={{ borderColor: SUBJECT_COLORS[currentQuestion.subject] ?? '#7C3AED' }}>
                <div className="border-b-4 border-ink px-5 py-3 bg-ink flex items-center justify-between flex-wrap gap-3">
                  <div className="flex items-center gap-3">
                    <span className="font-mono text-xs font-black text-yellow-bright">Q{currentQ + 1}</span>
                    <span className="font-mono text-[9px] text-white/50 border border-white/20 px-2 py-0.5 uppercase tracking-wider">
                      {currentQuestion.marks} Mark{currentQuestion.marks > 1 ? 's' : ''}
                    </span>
                    <span className="font-mono text-[9px] border px-2 py-0.5 uppercase tracking-wider" style={{ borderColor: SUBJECT_COLORS[currentQuestion.subject] ?? '#7C3AED', color: SUBJECT_COLORS[currentQuestion.subject] ?? '#7C3AED' }}>
                      {currentQuestion.subject}
                    </span>
                  </div>
                  <button
                    onClick={toggleFlag}
                    className="font-mono text-[9px] border-2 px-3 py-1 uppercase font-bold tracking-wider transition-colors"
                    style={isFlagged ? { backgroundColor: '#CA8A04', borderColor: '#CA8A04', color: 'white' } : { borderColor: 'rgba(255,255,255,0.3)', color: 'rgba(255,255,255,0.5)' }}
                  >
                    {isFlagged ? '⚑ Flagged' : '⚐ Flag for Review'}
                  </button>
                </div>

                <div className="p-6">
                  <p className="font-display text-lg md:text-xl font-black text-ink leading-snug mb-6">{currentQuestion.question}</p>
                  <div className="space-y-3">
                    {currentQuestion.options.map((opt, optIdx) => {
                      const isSelected = currentAnswer === optIdx
                      return (
                        <button
                          key={optIdx}
                          onClick={() => handleSelect(optIdx)}
                          className="w-full text-left border-4 border-ink p-4 flex items-center gap-4 transition-all"
                          style={{
                            backgroundColor: isSelected ? '#7C3AED' : 'white',
                            color: isSelected ? 'white' : '#0A0A0A',
                            boxShadow: isSelected ? '0px 0px 0px 0px #000' : '3px 3px 0px 0px #0A0A0A'
                          }}
                        >
                          <span
                            className="font-mono text-xs font-black border-2 border-ink w-6 h-6 flex items-center justify-center flex-shrink-0"
                            style={{
                              backgroundColor: isSelected ? 'white' : '#F3F4F6',
                              color: '#0A0A0A',
                            }}
                          >
                            {['A', 'B', 'C', 'D'][optIdx]}
                          </span>
                          <span className="text-sm font-bold leading-relaxed">{opt}</span>
                        </button>
                      )
                    })}
                  </div>

                  {/* Actions */}
                  <div className="flex justify-between items-center gap-3 mt-8 pt-6 border-t-2 border-ink/10 flex-wrap">
                    <button
                      onClick={() => setAnswers(prev => {
                        const copy = { ...prev }
                        delete copy[currentQuestion.id]
                        return copy
                      })}
                      className="border-4 border-ink px-4 py-2.5 bg-white text-ink hover:bg-gray-100 font-mono text-xs font-black uppercase tracking-wider"
                    >
                      Clear Response
                    </button>
                    <div className="flex gap-2">
                      <button
                        disabled={currentQ === 0}
                        onClick={() => setCurrentQ(prev => prev - 1)}
                        className="border-4 border-ink px-4 py-2.5 bg-white text-ink hover:bg-gray-100 disabled:opacity-50 font-mono text-xs font-black uppercase tracking-wider"
                      >
                        Previous
                      </button>
                      {currentQ < GATE_QUESTIONS.length - 1 ? (
                        <button
                          onClick={() => setCurrentQ(prev => prev + 1)}
                          className="border-4 border-ink px-5 py-2.5 bg-ink text-yellow-bright hover:bg-ink/90 font-mono text-xs font-black uppercase tracking-wider"
                        >
                          Next
                        </button>
                      ) : (
                        <button
                          onClick={handleSubmit}
                          className="border-4 border-ink px-5 py-2.5 bg-green text-white hover:opacity-90 font-mono text-xs font-black uppercase tracking-wider"
                        >
                          Submit Test
                        </button>
                      )}
                    </div>
                  </div>

                </div>
              </div>
            </div>

            {/* Sidebar Column */}
            <div className="lg:col-span-1 space-y-4">
              <div className="border-4 border-ink bg-canvas shadow-hard">
                <div className="border-b-4 border-ink px-4 py-3 bg-ink">
                  <span className="font-mono text-[10px] font-black text-yellow-bright uppercase tracking-widest">Question Palette</span>
                </div>
                <div className="p-4">
                  <div className="grid grid-cols-5 gap-2">
                    {GATE_QUESTIONS.map((q, idx) => {
                      const isQAnswered = answers[q.id] !== undefined
                      const isQFlagged = flagged.has(q.id)
                      const isQCurrent = idx === currentQ
                      
                      let bg = 'white'
                      let text = 'text-ink'
                      
                      if (isQCurrent) {
                        bg = '#7C3AED'
                        text = 'text-white'
                      } else if (isQFlagged) {
                        bg = '#CA8A04'
                        text = 'text-white'
                      } else if (isQAnswered) {
                        bg = '#15803D'
                        text = 'text-white'
                      }
                      
                      return (
                        <button
                          key={q.id}
                          onClick={() => setCurrentQ(idx)}
                          className="w-10 h-10 border-4 border-ink flex items-center justify-center font-mono font-black text-xs transition-colors"
                          style={{ backgroundColor: bg, color: text }}
                        >
                          {idx + 1}
                        </button>
                      )
                    })}
                  </div>
                  
                  <div className="mt-6 border-t-2 border-ink/10 pt-4 space-y-2">
                    <div className="flex items-center gap-2 text-xs">
                      <span className="w-4 h-4 border-2 border-ink bg-[#15803D]" />
                      <span className="text-ink/75 font-medium">Answered ({answered})</span>
                    </div>
                    <div className="flex items-center gap-2 text-xs">
                      <span className="w-4 h-4 border-2 border-ink bg-[#CA8A04]" />
                      <span className="text-ink/75 font-medium">Flagged ({flagged.size})</span>
                    </div>
                    <div className="flex items-center gap-2 text-xs">
                      <span className="w-4 h-4 border-2 border-ink bg-white" />
                      <span className="text-ink/75 font-medium">Not Attempted ({GATE_QUESTIONS.length - answered})</span>
                    </div>
                  </div>
                  
                  <button
                    onClick={handleSubmit}
                    className="w-full mt-6 border-4 border-ink bg-green text-white py-3 font-mono font-black text-xs uppercase tracking-widest hover:opacity-90 transition-opacity shadow-hard-sm"
                  >
                    Submit Test
                  </button>
                </div>
              </div>
            </div>

          </div>
        )}

        {/* Submitted state */}
        {state === 'submitted' && (
          <ScoreReport answers={answers} timeTaken={timeTaken} />
        )}
      </div>
    </div>
  )
}
